"""
this is class where we are importing all of the data of the block and just we will 
use this class as a constructer.
use case = "Major use"
made: 15/5
no_of updated = 14
last_update: 17/6
"""

from time import time

from utility.printable import Printable

class Block(Printable):
    """A single block of our blockchain.
    
    Attributes:
        :index: The index of this block.
        :previous_hash: The hash of the previous block in the blockchain.
        :timestamp: The timestamp of the block (automatically generated by default).
        :transactions: A list of transaction which are included in the block.
        :proof: The proof of work number that yielded this block.
    """
    def __init__(self, index, previous_hash, transactions, proof, time=time()):
        self.index = index
        self.previous_hash = previous_hash
        self.timestamp = time
        self.transactions = transactions
        self.proof = proof


